"""Structured logging, request correlation, and secret redaction.

`request_id` is a ULID generated by the outermost middleware and carried in a
contextvar so that any log line anywhere in the request — including inside a
threadpool-executed sync route handler — is correlated without threading an
argument through every function signature.

The redaction processor is not decoration. Document text, auth headers and
upstream API keys all pass through this process, and a single
`log.info("call", headers=request.headers)` would otherwise put a bearer token
in the container logs permanently.
"""

from __future__ import annotations

import logging
import re
import secrets
import sys
import time
from contextvars import ContextVar
from typing import Any

import structlog

# ── request id ───────────────────────────────────────────────────────────────

# Crockford base32: no I, L, O or U, so a ULID cannot be misread aloud during a
# demo when someone reads an error id off a toast.
_CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"

_request_id: ContextVar[str | None] = ContextVar("request_id", default=None)


def new_request_id() -> str:
    """Generate a 26-character ULID.

    48 bits of millisecond timestamp followed by 80 bits of randomness, so ids
    sort chronologically — useful when grepping logs for "what happened right
    before this error".
    """
    value = (int(time.time() * 1000) << 80) | secrets.randbits(80)
    out = bytearray(26)
    for i in range(25, -1, -1):
        out[i] = ord(_CROCKFORD[value & 0x1F])
        value >>= 5
    return out.decode("ascii")


def set_request_id(request_id: str) -> None:
    _request_id.set(request_id)
    structlog.contextvars.bind_contextvars(request_id=request_id)


def get_request_id() -> str | None:
    return _request_id.get()


def clear_request_context() -> None:
    _request_id.set(None)
    structlog.contextvars.clear_contextvars()


# ── redaction ────────────────────────────────────────────────────────────────

# Matched case-insensitively against the *key*, as a substring. Broad on
# purpose: a false positive costs one unreadable log field, a false negative
# costs a leaked credential.
_SENSITIVE_KEY_PATTERN = re.compile(
    r"(password|passwd|secret|token|api_key|apikey|authorization|auth_header"
    r"|cookie|cs_refresh|credential|private_key|session_id|jwt)",
    re.IGNORECASE,
)

# Catches a bearer token or an API key that ended up inside a *value* — for
# example in an exception message from an HTTP client that echoes the request.
_SENSITIVE_VALUE_PATTERNS = [
    re.compile(r"Bearer\s+[A-Za-z0-9._\-]{10,}", re.IGNORECASE),
    re.compile(r"\bnvapi-[A-Za-z0-9._\-]{8,}"),  # NVIDIA / Nemotron
    re.compile(r"\bsk_[A-Za-z0-9]{8,}"),  # ElevenLabs-style
    re.compile(r"\beyJ[A-Za-z0-9._\-]{20,}"),  # anything JWT-shaped
]

REDACTED = "«redacted»"
_MAX_DEPTH = 6


def _scrub(value: Any, depth: int = 0) -> Any:
    if depth > _MAX_DEPTH:
        return "«depth-limit»"
    if isinstance(value, dict):
        out: dict[Any, Any] = {}
        for k, v in value.items():
            if isinstance(k, str) and _SENSITIVE_KEY_PATTERN.search(k):
                out[k] = REDACTED
            else:
                out[k] = _scrub(v, depth + 1)
        return out
    if isinstance(value, (list, tuple, set)):
        scrubbed = [_scrub(v, depth + 1) for v in value]
        return type(value)(scrubbed) if isinstance(value, (list, tuple)) else set(scrubbed)
    if isinstance(value, str):
        for pattern in _SENSITIVE_VALUE_PATTERNS:
            value = pattern.sub(REDACTED, value)
        return value
    return value


def redact_processor(
    _logger: Any, _name: str, event_dict: structlog.types.EventDict
) -> structlog.types.EventDict:
    """structlog processor that scrubs credentials from every log event."""
    return _scrub(event_dict)  # type: ignore[return-value]


# ── configuration ────────────────────────────────────────────────────────────


def configure_logging(level: str = "INFO", json_output: bool | None = None) -> None:
    """Configure structlog and route stdlib logging through it.

    `json_output` defaults to True when the level is not DEBUG, on the
    assumption that DEBUG means a human is watching a terminal.
    """
    if json_output is None:
        json_output = level != "DEBUG"

    # NOTE: the `structlog.processors.*` variants, not `structlog.stdlib.*`.
    # The logger factory below is `PrintLoggerFactory`, and the stdlib
    # processors assume a stdlib logger — `structlog.stdlib.add_logger_name`
    # reads `logger.name`, which `PrintLogger` does not have, and raises
    # AttributeError on the first log call. The module name is bound in
    # `get_logger` instead, which is logger-agnostic.
    shared: list[structlog.types.Processor] = [
        structlog.contextvars.merge_contextvars,
        structlog.processors.add_log_level,
        structlog.processors.TimeStamper(fmt="iso", utc=True),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.UnicodeDecoder(),
        redact_processor,
    ]

    renderer: structlog.types.Processor = (
        structlog.processors.JSONRenderer()
        if json_output
        else structlog.dev.ConsoleRenderer(colors=sys.stderr.isatty())
    )

    structlog.configure(
        processors=[
            *shared,
            structlog.processors.format_exc_info,
            renderer,
        ],
        wrapper_class=structlog.make_filtering_bound_logger(
            logging.getLevelNamesMapping()[level]
        ),
        logger_factory=structlog.PrintLoggerFactory(file=sys.stdout),
        cache_logger_on_first_use=True,
    )

    # Bring uvicorn/sqlalchemy/alembic output into the same stream and format.
    logging.basicConfig(
        format="%(message)s",
        stream=sys.stdout,
        level=logging.getLevelNamesMapping()[level],
        force=True,
    )
    for noisy in ("uvicorn.access", "uvicorn.error", "multipart", "httpx", "httpcore"):
        logging.getLogger(noisy).setLevel(max(logging.WARNING, logging.getLevelNamesMapping()[level]))


def get_logger(name: str | None = None) -> structlog.stdlib.BoundLogger:
    """Return a logger with the module name bound as `logger`.

    The name is bound rather than derived by a processor, because
    `PrintLogger` carries no `.name` attribute (see the note in
    `configure_logging`).

    `structlog.get_logger()` returns a lazy proxy and `.bind()` on that proxy
    returns another lazy proxy, so the underlying logger is still not
    materialized here. That matters: every module does
    `log = get_logger(__name__)` at import time, which is well before
    `configure_logging()` runs in the lifespan. Staying lazy means those
    module-level loggers pick up the real configuration rather than caching
    structlog's defaults.
    """
    logger = structlog.get_logger()
    if name:
        logger = logger.bind(logger=name)
    return logger  # type: ignore[no-any-return]
