"""FastAPI application factory.

Run it:
    uvicorn api.main:app --reload            # real pipeline
    MOCK_MODE=1 uvicorn api.main:app         # fixtures, for the frontend

OpenAPI lives at /api/v1/openapi.json and the docs at /api/v1/docs, because the
frontend generates its TypeScript types from that schema and the path is part
of the contract (frontend brief §4.1).
"""

from __future__ import annotations

import random
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from api.errors import NotFound, register_exception_handlers
from api.middleware import (
    RequestContextMiddleware,
    RequestSizeLimitMiddleware,
    SecurityHeadersMiddleware,
)
from api.mock import BUILD_STAGE
from api.v1 import api_router
from core.config import Settings, fatal_config_exit, get_settings
from core.logging import configure_logging, get_logger
from core.ratelimit import limiter
from db.session import check_database

log = get_logger(__name__)

API_VERSION = "0.1.0"


def _seed_everything(seed: int) -> None:
    """Make the pipeline reproducible.

    Judges re-run things, and the number on the slide has to be the number on
    stage. torch and numpy are seeded lazily — importing torch at app start
    costs seconds we do not need to spend until a model is actually loaded.
    """
    random.seed(seed)
    try:
        import numpy as np

        np.random.seed(seed % (2**32))
    except ImportError:  # pragma: no cover - numpy is a hard dependency in prod
        pass


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    settings: Settings = app.state.settings
    configure_logging(level=settings.log_level)
    _seed_everything(settings.pipeline_seed)

    log.info(
        "startup",
        environment=str(settings.environment),
        mock_mode=settings.mock_mode,
        build_stage=BUILD_STAGE,
        relation_model=str(settings.relation_model),
        vacuity_gate_threshold=settings.vacuity_gate_threshold,
        pipeline_seed=settings.pipeline_seed,
        database_reachable=check_database(),
        nemotron_configured=bool(settings.nemotron_api_key),
        elevenlabs_configured=bool(settings.elevenlabs_api_key),
        serve_static=settings.serve_static,
        voice_fallback_recorded=settings.path(settings.voice_fallback_audio).is_file(),
    )

    # Loud about missing upstream keys at boot rather than at hour 20. Not
    # fatal: the cascade degrades to classical and voice falls back to the
    # prerecorded briefing, both of which are demo paths we test on purpose.
    if not settings.mock_mode:
        if not settings.nemotron_api_key:
            log.warning("nemotron_key_missing", effect="cascade will run classical-only")
        if not settings.elevenlabs_api_key:
            log.warning("elevenlabs_key_missing", effect="voice will serve the fallback briefing")

    yield

    log.info("shutdown")


def create_app(settings: Settings | None = None) -> FastAPI:
    settings = settings or get_settings()

    if problems := settings.check_production_safety():
        fatal_config_exit(problems)

    app = FastAPI(
        title="COUNTERSIGN",
        version=API_VERSION,
        description=(
            "Uncertainty-gated financial risk extraction. Every insight carries a "
            "byte-exact citation; no response text is generated by a language model."
        ),
        openapi_url="/api/v1/openapi.json",
        docs_url="/api/v1/docs",
        redoc_url=None,
        lifespan=lifespan,
    )
    app.state.settings = settings
    app.state.limiter = limiter

    register_exception_handlers(app)

    # ── middleware ───────────────────────────────────────────────────────────
    # Starlette's add_middleware inserts at the FRONT of the list and the stack
    # is built by wrapping in reverse, so the LAST one added is the OUTERMOST.
    # These are therefore added innermost-first. Resulting order, outside in:
    #
    #   RequestContext  -> ids and logging wrap everything, including errors
    #   CORS            -> so error envelopes still carry CORS headers
    #   SecurityHeaders
    #   RequestSizeLimit-> reject oversized bodies before anything buffers them
    #   GZip            -> innermost; compresses the final body
    app.add_middleware(GZipMiddleware, minimum_size=1_024)
    app.add_middleware(RequestSizeLimitMiddleware, max_bytes=settings.max_request_bytes)
    app.add_middleware(SecurityHeadersMiddleware, settings=settings)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origin_list,
        # Required for the HttpOnly refresh cookie to travel. Incompatible with
        # a wildcard origin, which is why config.py rejects '*'.
        allow_credentials=True,
        allow_methods=["GET", "POST", "PATCH", "DELETE", "OPTIONS"],
        allow_headers=["Authorization", "Content-Type", "Idempotency-Key", "X-Request-ID"],
        expose_headers=["X-Request-ID", "Retry-After", "Content-Range", "Accept-Ranges"],
        max_age=600,
    )
    app.add_middleware(RequestContextMiddleware)

    app.include_router(api_router)
    _register_health(app, settings)
    # Must come last: the SPA catch-all matches everything, and Starlette
    # resolves routes in registration order, so the API and health routes have
    # to be in place before it.
    _register_static(app, settings)

    return app


# Paths the SPA catch-all must never answer for. Without this, a typo'd API
# call would get 200 text/html instead of the error envelope the frontend
# switches on (brief §3), which is a genuinely confusing way to lose an hour.
_API_PREFIXES = ("api/", "health")


def _register_static(app: FastAPI, settings: Settings) -> None:
    """Serve the built frontend from this process when SERVE_STATIC is set.

    `docker-compose.prod.yml` builds the frontend to a volume, mounts it at
    `STATIC_DIR` in this container and publishes only port 8000, so the whole
    app is one origin — which is what makes brief §16's "`docker compose up`
    ... serves the frontend build" and plan §4 Stage 10's "`make prod`
    single-origin build serving the frontend bundle" true rather than
    aspirational. Until this function existed, `SERVE_STATIC` was read in
    exactly one place (the CSP in `api/middleware.py`) and the bundle was
    mounted, copied and never served: the API answered and `/` returned 404.

    Deliberately non-fatal when the bundle is missing. A backend that refuses
    to boot because a frontend build is absent is useless for backend work,
    and `MOCK_MODE`/dev never set this flag at all.
    """
    if not settings.serve_static:
        return

    root = Path(settings.static_dir).resolve()
    index = root / "index.html"

    # Everything below resolves paths *per request*, not at startup. The
    # frontend container builds for a minute or two and then copies into the
    # shared volume, and it cannot be a compose `depends_on` of the backend
    # (the base file already has the frontend depending on the backend, so
    # that would be a cycle). A startup-time existence check would therefore
    # lose the race on a cold `make prod` and strand the bundle: files
    # present, routes never registered, `/` 404 until someone restarted the
    # API. Checking per request also means a rebuilt bundle is picked up
    # without a restart.
    if index.is_file():
        log.info("serving_static_bundle", static_dir=str(root))
    else:
        log.warning(
            "static_bundle_not_ready",
            static_dir=str(root),
            effect="/ returns 404 until the frontend build lands; API is unaffected",
            hint="expected during a cold `make prod` while the frontend image builds",
        )

    # Vite emits absolute `/assets/...` URLs with content-hashed filenames, so
    # they are safe to cache hard. StaticFiles handles conditional GETs and
    # ranges for them, and is mounted lazily for the same race reason: a
    # `StaticFiles(directory=...)` constructed against a missing directory
    # raises at startup.
    assets = root / "assets"
    if assets.is_dir():
        app.mount("/assets", StaticFiles(directory=assets), name="assets")
    else:
        # Fall through to the catch-all below, which serves any real file it
        # finds — including `assets/*` — just without StaticFiles' caching
        # niceties. Correct output either way.
        log.info("static_assets_dir_absent_using_catch_all", assets_dir=str(assets))

    @app.get("/{spa_path:path}", include_in_schema=False)
    def spa(spa_path: str) -> FileResponse:
        """Real file if one exists, else `index.html` for client-side routing.

        Frontend brief §3 requires every app screen to be deep-linkable
        (`/app/feed/:insightId`, `/app/document/:docId?span=…`) so the demo
        can jump straight to any surface if something breaks live. Those paths
        exist only in the router, so a hard reload has to return the shell and
        let React resolve them.
        """
        if spa_path.startswith(_API_PREFIXES):
            # Past the real API routes and still starting with /api — this is
            # a 404 on the API, not a page.
            raise NotFound("No such endpoint.", details={"path": f"/{spa_path}"})

        if spa_path:
            candidate = (root / spa_path).resolve()
            # `resolve()` collapses `..` before this check, so a traversal
            # attempt lands outside `root` and is rejected rather than
            # reaching the filesystem.
            if candidate.is_relative_to(root) and candidate.is_file():
                return FileResponse(candidate)

        if not index.is_file():
            raise NotFound(
                "The frontend bundle is not built yet.",
                details={"static_dir": str(root), "hint": "make prod"},
            )

        # `index.html` names hashed assets, so caching it would pin a browser
        # to a stale bundle across a rebuild — exactly the failure that looks
        # like "the fix didn't deploy" at hour 23.
        return FileResponse(index, headers={"Cache-Control": "no-cache"})


def _register_health(app: FastAPI, settings: Settings) -> None:
    @app.get("/health", tags=["meta"], include_in_schema=False)
    def health() -> dict[str, Any]:
        """Liveness. Always 200 while the process is serving.

        Deliberately does not fail when Postgres is unreachable: the Docker
        healthcheck polls this, and a DB blip returning 503 would mark the
        container unhealthy and restart-loop the API in the middle of a demo.
        Readiness is the endpoint that cares about dependencies.
        """
        return {
            "status": "ok",
            "version": API_VERSION,
            "environment": str(settings.environment),
            "mock_mode": settings.mock_mode,
            "build_stage": BUILD_STAGE,
            "database": "up" if check_database() else "down",
        }

    @app.get("/health/ready", tags=["meta"], include_in_schema=False)
    def readiness() -> Any:
        """Readiness. 503 when a hard dependency is down."""
        from fastapi.responses import JSONResponse

        db_ok = check_database()
        payload = {"status": "ready" if db_ok else "not_ready", "database": db_ok}
        return JSONResponse(payload, status_code=200 if db_ok else 503)


app = create_app()
