"""FastAPI application factory.

Run it:
    uvicorn api.main:app --reload            # real pipeline
    MOCK_MODE=1 uvicorn api.main:app         # fixtures, for the frontend

OpenAPI lives at /api/v1/openapi.json and the docs at /api/v1/docs, because the
frontend generates its TypeScript types from that schema and the path is part
of the contract (frontend brief §4.1).
"""

from __future__ import annotations

import random
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware

from api.errors import register_exception_handlers
from api.middleware import (
    RequestContextMiddleware,
    RequestSizeLimitMiddleware,
    SecurityHeadersMiddleware,
)
from api.mock import BUILD_STAGE
from api.v1 import api_router
from core.config import Settings, fatal_config_exit, get_settings
from core.logging import configure_logging, get_logger
from core.ratelimit import limiter
from db.session import check_database

log = get_logger(__name__)

API_VERSION = "0.1.0"


def _seed_everything(seed: int) -> None:
    """Make the pipeline reproducible.

    Judges re-run things, and the number on the slide has to be the number on
    stage. torch and numpy are seeded lazily — importing torch at app start
    costs seconds we do not need to spend until a model is actually loaded.
    """
    random.seed(seed)
    try:
        import numpy as np

        np.random.seed(seed % (2**32))
    except ImportError:  # pragma: no cover - numpy is a hard dependency in prod
        pass


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    settings: Settings = app.state.settings
    configure_logging(level=settings.log_level)
    _seed_everything(settings.pipeline_seed)

    log.info(
        "startup",
        environment=str(settings.environment),
        mock_mode=settings.mock_mode,
        build_stage=BUILD_STAGE,
        relation_model=str(settings.relation_model),
        vacuity_gate_threshold=settings.vacuity_gate_threshold,
        pipeline_seed=settings.pipeline_seed,
        database_reachable=check_database(),
        nemotron_configured=bool(settings.nemotron_api_key),
        elevenlabs_configured=bool(settings.elevenlabs_api_key),
    )

    # Loud about missing upstream keys at boot rather than at hour 20. Not
    # fatal: the cascade degrades to classical and voice falls back to the
    # prerecorded briefing, both of which are demo paths we test on purpose.
    if not settings.mock_mode:
        if not settings.nemotron_api_key:
            log.warning("nemotron_key_missing", effect="cascade will run classical-only")
        if not settings.elevenlabs_api_key:
            log.warning("elevenlabs_key_missing", effect="voice will serve the fallback briefing")

    yield

    log.info("shutdown")


def create_app(settings: Settings | None = None) -> FastAPI:
    settings = settings or get_settings()

    if problems := settings.check_production_safety():
        fatal_config_exit(problems)

    app = FastAPI(
        title="COUNTERSIGN",
        version=API_VERSION,
        description=(
            "Uncertainty-gated financial risk extraction. Every insight carries a "
            "byte-exact citation; no response text is generated by a language model."
        ),
        openapi_url="/api/v1/openapi.json",
        docs_url="/api/v1/docs",
        redoc_url=None,
        lifespan=lifespan,
    )
    app.state.settings = settings
    app.state.limiter = limiter

    register_exception_handlers(app)

    # ── middleware ───────────────────────────────────────────────────────────
    # Starlette's add_middleware inserts at the FRONT of the list and the stack
    # is built by wrapping in reverse, so the LAST one added is the OUTERMOST.
    # These are therefore added innermost-first. Resulting order, outside in:
    #
    #   RequestContext  -> ids and logging wrap everything, including errors
    #   CORS            -> so error envelopes still carry CORS headers
    #   SecurityHeaders
    #   RequestSizeLimit-> reject oversized bodies before anything buffers them
    #   GZip            -> innermost; compresses the final body
    app.add_middleware(GZipMiddleware, minimum_size=1_024)
    app.add_middleware(RequestSizeLimitMiddleware, max_bytes=settings.max_request_bytes)
    app.add_middleware(SecurityHeadersMiddleware, settings=settings)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origin_list,
        # Required for the HttpOnly refresh cookie to travel. Incompatible with
        # a wildcard origin, which is why config.py rejects '*'.
        allow_credentials=True,
        allow_methods=["GET", "POST", "PATCH", "DELETE", "OPTIONS"],
        allow_headers=["Authorization", "Content-Type", "Idempotency-Key", "X-Request-ID"],
        expose_headers=["X-Request-ID", "Retry-After", "Content-Range", "Accept-Ranges"],
        max_age=600,
    )
    app.add_middleware(RequestContextMiddleware)

    app.include_router(api_router)
    _register_health(app, settings)

    return app


def _register_health(app: FastAPI, settings: Settings) -> None:
    @app.get("/health", tags=["meta"], include_in_schema=False)
    def health() -> dict[str, Any]:
        """Liveness. Always 200 while the process is serving.

        Deliberately does not fail when Postgres is unreachable: the Docker
        healthcheck polls this, and a DB blip returning 503 would mark the
        container unhealthy and restart-loop the API in the middle of a demo.
        Readiness is the endpoint that cares about dependencies.
        """
        return {
            "status": "ok",
            "version": API_VERSION,
            "environment": str(settings.environment),
            "mock_mode": settings.mock_mode,
            "build_stage": BUILD_STAGE,
            "database": "up" if check_database() else "down",
        }

    @app.get("/health/ready", tags=["meta"], include_in_schema=False)
    def readiness() -> Any:
        """Readiness. 503 when a hard dependency is down."""
        from fastapi.responses import JSONResponse

        db_ok = check_database()
        payload = {"status": "ready" if db_ok else "not_ready", "database": db_ok}
        return JSONResponse(payload, status_code=200 if db_ok else 503)


app = create_app()
