"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-19

Hand-written rather than autogenerated, for three reasons:

  1. The PG enum types have to be created before the tables that reference
     them, and autogenerate's ordering for `create_type=False` enums is not
     reliable.
  2. The pgvector HNSW index and the pg_trgm GIN index need `USING` clauses and
     operator classes that autogenerate emits inconsistently.
  3. `calibration_snapshots.idempotency_key` needs a *partial* unique index,
     which autogenerate does not produce from the model at all.

Extensions are also created here, idempotently. `docker/postgres/init/` only
runs on a brand-new volume, so a developer who already had a `countersign`
volume before pgvector was added would otherwise hit a confusing type error.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


USER_ROLE = ("owner", "analyst", "viewer")
DOC_SOURCE = (
    "invoice",
    "email",
    "press_release",
    "rss",
    "gdelt",
    "note",
    "transaction_log",
)
ROUTING_BUCKET = ("auto_file", "flag_for_review", "escalate_now")
RESOLVER = ("classical", "nemotron")
JOB_STATE = (
    "queued",
    "tagging",
    "parsing",
    "relating",
    "scoring",
    "routing",
    "done",
    "failed",
)

_ENUMS = {
    "user_role": USER_ROLE,
    "doc_source": DOC_SOURCE,
    "routing_bucket": ROUTING_BUCKET,
    "resolver": RESOLVER,
    "job_state": JOB_STATE,
}


def _enum(name: str) -> postgresql.ENUM:
    """Reference an already-created type without trying to create it again."""
    return postgresql.ENUM(*_ENUMS[name], name=name, create_type=False)


def upgrade() -> None:
    bind = op.get_bind()

    # ── extensions ───────────────────────────────────────────────────────────
    for extension in ("pgcrypto", "citext", "vector", "pg_trgm"):
        op.execute(f'CREATE EXTENSION IF NOT EXISTS "{extension}"')

    # ── enum types ───────────────────────────────────────────────────────────
    for name, values in _ENUMS.items():
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)

    # ── organizations ────────────────────────────────────────────────────────
    op.create_table(
        "organizations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_organizations"),
    )

    # ── users ────────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", _enum("user_role"), server_default=sa.text("'viewer'"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("failed_logins", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("first_failed_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name="fk_users_org_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_org_id", "users", ["org_id"])

    # ── refresh_tokens ───────────────────────────────────────────────────────
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_refresh_tokens_user_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_refresh_tokens"),
    )
    op.create_index("ix_refresh_tokens_token_hash", "refresh_tokens", ["token_hash"], unique=True)
    op.create_index(
        "ix_refresh_tokens_user_id_revoked_at", "refresh_tokens", ["user_id", "revoked_at"]
    )
    op.create_index("ix_refresh_tokens_family_id", "refresh_tokens", ["family_id"])

    # ── documents ────────────────────────────────────────────────────────────
    op.create_table(
        "documents",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source", _enum("doc_source"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("content_sha", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "meta", postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name="fk_documents_org_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_documents"),
    )
    op.create_index(
        "ix_documents_org_id_content_sha", "documents", ["org_id", "content_sha"], unique=True
    )
    op.execute(
        "CREATE INDEX ix_documents_org_id_received_at "
        "ON documents (org_id, received_at DESC)"
    )

    # ── entities ─────────────────────────────────────────────────────────────
    op.create_table(
        "entities",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("canonical", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(256), nullable=True),
        sa.Column(
            "aliases",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "first_seen", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("mention_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "entity_type IN ('ORG','PERSON','MONEY','DATE','ACCOUNT_REF','TRANSACTION_TYPE')",
            name="ck_entities_entity_type_known",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name="fk_entities_org_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_entities"),
    )
    op.create_index("ix_entities_org_id_entity_type", "entities", ["org_id", "entity_type"])
    op.execute(
        "CREATE INDEX ix_entities_embedding_hnsw ON entities "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    # ── mentions ─────────────────────────────────────────────────────────────
    op.create_table(
        "mentions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("document_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("surface", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("tagger_conf", sa.Float(), nullable=False),
        sa.CheckConstraint("char_end > char_start", name="ck_mentions_span_ordered"),
        sa.CheckConstraint("char_start >= 0", name="ck_mentions_span_non_negative"),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.id"], name="fk_mentions_entity_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name="fk_mentions_document_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_mentions"),
    )
    op.create_index(
        "ix_mentions_document_id_char_start", "mentions", ["document_id", "char_start"]
    )
    op.create_index("ix_mentions_entity_id", "mentions", ["entity_id"])

    # ── nemotron_runs (before insights: insights references it) ──────────────
    op.create_table(
        "nemotron_runs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("insight_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("prompt_sha", sa.String(length=64), nullable=False),
        sa.Column("decision", _enum("routing_bucket"), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("degraded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_nemotron_runs"),
    )
    op.execute(
        "CREATE INDEX ix_nemotron_runs_org_id_created_at "
        "ON nemotron_runs (org_id, created_at DESC)"
    )

    # ── insights ─────────────────────────────────────────────────────────────
    op.create_table(
        "insights",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("document_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("subject_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("object_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("relation", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("sentence_text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("vacuity", sa.Float(), nullable=False),
        sa.Column("dissonance", sa.Float(), nullable=False),
        sa.Column("fragility", sa.Float(), nullable=True),
        sa.Column("routing", _enum("routing_bucket"), nullable=False),
        sa.Column("resolved_by", _enum("resolver"), nullable=False),
        sa.Column("nemotron_run_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("degraded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("classical_routing", _enum("routing_bucket"), nullable=True),
        sa.Column(
            "attention", postgresql.JSONB(), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column(
            "tokens", postgresql.JSONB(), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("evidence_logits", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("char_end > char_start", name="ck_insights_span_ordered"),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_insights_confidence_unit"
        ),
        sa.CheckConstraint("vacuity >= 0 AND vacuity <= 1", name="ck_insights_vacuity_unit"),
        sa.CheckConstraint(
            "dissonance >= 0 AND dissonance <= 1", name="ck_insights_dissonance_unit"
        ),
        sa.CheckConstraint(
            "fragility IS NULL OR (fragility >= 0 AND fragility <= 1)",
            name="ck_insights_fragility_unit",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name="fk_insights_org_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name="fk_insights_document_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["entities.id"], name="fk_insights_subject_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["object_id"], ["entities.id"], name="fk_insights_object_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["nemotron_run_id"],
            ["nemotron_runs.id"],
            name="fk_insights_nemotron_run_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_insights"),
    )
    op.execute(
        "CREATE INDEX ix_insights_org_id_routing_created_at "
        "ON insights (org_id, routing, created_at DESC)"
    )
    op.execute("CREATE INDEX ix_insights_org_id_vacuity ON insights (org_id, vacuity DESC)")
    op.create_index("ix_insights_document_id", "insights", ["document_id"])
    op.create_index("ix_insights_subject_id", "insights", ["subject_id"])
    op.create_index("ix_insights_object_id", "insights", ["object_id"])
    op.execute(
        "CREATE INDEX ix_insights_sentence_text_trgm ON insights "
        "USING gin (sentence_text gin_trgm_ops)"
    )

    # ── ablation_runs ────────────────────────────────────────────────────────
    op.create_table(
        "ablation_runs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("insight_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("masked_edges", postgresql.JSONB(), nullable=False),
        sa.Column("mode", sa.Text(), server_default=sa.text("'zero'"), nullable=False),
        sa.Column("confidence_before", sa.Float(), nullable=False),
        sa.Column("confidence_after", sa.Float(), nullable=False),
        sa.Column("vacuity_before", sa.Float(), nullable=False),
        sa.Column("vacuity_after", sa.Float(), nullable=False),
        sa.Column("routing_before", _enum("routing_bucket"), nullable=False),
        sa.Column("routing_after", _enum("routing_bucket"), nullable=False),
        sa.Column("relation_before", sa.Text(), nullable=False),
        sa.Column("relation_after", sa.Text(), nullable=False),
        sa.Column("load_bearing", sa.Boolean(), nullable=False),
        sa.Column("interpretation", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("mode IN ('zero','uniform')", name="ck_ablation_runs_mode_known"),
        sa.ForeignKeyConstraint(
            ["insight_id"], ["insights.id"], name="fk_ablation_runs_insight_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_ablation_runs"),
    )
    op.execute(
        "CREATE INDEX ix_ablation_runs_insight_id_created_at "
        "ON ablation_runs (insight_id, created_at DESC)"
    )

    # ── fragility_trials ─────────────────────────────────────────────────────
    op.create_table(
        "fragility_trials",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("insight_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("perturbation", sa.Text(), nullable=False),
        sa.Column("variant", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("label_flipped", sa.Boolean(), nullable=False),
        sa.Column("conf_delta", sa.Float(), nullable=False),
        sa.Column("relation_lost", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "perturbation IN ('synonym','rename','boilerplate','reorder','punctuation')",
            name="ck_fragility_trials_perturbation_known",
        ),
        sa.ForeignKeyConstraint(
            ["insight_id"],
            ["insights.id"],
            name="fk_fragility_trials_insight_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_fragility_trials"),
    )
    op.create_index("ix_fragility_trials_insight_id", "fragility_trials", ["insight_id"])
    op.create_index("ix_fragility_trials_perturbation", "fragility_trials", ["perturbation"])

    # ── calibration_snapshots ────────────────────────────────────────────────
    op.create_table(
        "calibration_snapshots",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("ece", sa.Float(), nullable=False),
        sa.Column("mce", sa.Float(), nullable=False),
        sa.Column("brier", sa.Float(), nullable=False),
        sa.Column("bins", postgresql.JSONB(), nullable=False),
        sa.Column("n_cases", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "label IN ('baseline','post_recalibration')",
            name="ck_calibration_snapshots_label_known",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_calibration_snapshots_org_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_calibration_snapshots"),
    )
    op.execute(
        "CREATE INDEX ix_calibration_snapshots_org_id_created_at "
        "ON calibration_snapshots (org_id, created_at DESC)"
    )
    op.execute(
        "CREATE UNIQUE INDEX ix_calibration_snapshots_idempotency_key "
        "ON calibration_snapshots (org_id, idempotency_key) "
        "WHERE idempotency_key IS NOT NULL"
    )

    # ── routing_eval_cases ───────────────────────────────────────────────────
    op.create_table(
        "routing_eval_cases",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("insight_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("ground_truth", _enum("routing_bucket"), nullable=False),
        sa.Column("predicted", _enum("routing_bucket"), nullable=False),
        sa.Column("resolved_by", _enum("resolver"), nullable=False),
        sa.Column("split", sa.Text(), server_default=sa.text("'eval'"), nullable=False),
        sa.Column("gate_bypassed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_failure", sa.Boolean(), nullable=False),
        sa.Column("failure_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "split IN ('eval','classical_only','nemotron_all')",
            name="ck_routing_eval_cases_split_known",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_routing_eval_cases_org_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["insight_id"],
            ["insights.id"],
            name="fk_routing_eval_cases_insight_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_routing_eval_cases"),
    )
    op.create_index(
        "ix_routing_eval_cases_org_id_split", "routing_eval_cases", ["org_id", "split"]
    )
    op.create_index("ix_routing_eval_cases_insight_id", "routing_eval_cases", ["insight_id"])

    # ── ingest_jobs ──────────────────────────────────────────────────────────
    op.create_table(
        "ingest_jobs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("state", _enum("job_state"), server_default=sa.text("'queued'"), nullable=False),
        sa.Column("doc_ids", postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=False),
        sa.Column("docs_total", sa.Integer(), nullable=False),
        sa.Column("docs_done", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("insights_found", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "stage_progress",
            postgresql.JSONB(),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("scenario", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("error_stage", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name="fk_ingest_jobs_org_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_ingest_jobs"),
    )
    op.execute(
        "CREATE INDEX ix_ingest_jobs_org_id_created_at ON ingest_jobs (org_id, created_at DESC)"
    )


def downgrade() -> None:
    bind = op.get_bind()

    for table in (
        "ingest_jobs",
        "routing_eval_cases",
        "calibration_snapshots",
        "fragility_trials",
        "ablation_runs",
        "insights",
        "nemotron_runs",
        "mentions",
        "entities",
        "documents",
        "refresh_tokens",
        "users",
        "organizations",
    ):
        op.drop_table(table)

    for name in _ENUMS:
        postgresql.ENUM(name=name).drop(bind, checkfirst=True)
