"""Alembic environment.

Reads DATABASE_URL from the environment rather than alembic.ini so the same
config works locally, in Docker, and in CI without editing files.

Once db/models.py exists, uncomment the two lines marked TODO and
`make migration m="initial schema"` will autogenerate from the models.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

database_url = os.getenv("DATABASE_URL")
if not database_url:
    raise RuntimeError("DATABASE_URL is not set")
config.set_main_option("sqlalchemy.url", database_url.replace("%", "%%"))

# Importable because alembic.ini sets `prepend_sys_path = .`, so alembic must
# be invoked from the backend/ directory (which is what `make migrate` does).
from db.models import Base  # noqa: E402

target_metadata = Base.metadata


def include_object(obj, name, type_, reflected, compare_to) -> bool:
    """Keep extension internals out of autogenerated migrations.

    The initial migration is hand-written (see
    versions/20260919_1600_initial_schema.py for why), and autogenerate is only
    used for incremental changes after it. Two things it gets wrong here:

    - extension-owned tables, which it wants to drop
    - the pgvector HNSW and pg_trgm GIN indexes, which it re-emits without the
      operator class, producing an index that is valid SQL and useless
    """
    if type_ == "table" and name in {"spatial_ref_sys"}:
        return False
    if type_ == "index" and name in {
        "ix_entities_embedding_hnsw",
        "ix_insights_sentence_text_trgm",
    }:
        return False
    return True


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
            include_object=include_object,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
