"""Every request and response model for /api/v1.

This module is the machine-readable form of 01-BACKEND-BRIEF.md §4—§11. The
frontend generates its TypeScript from the OpenAPI schema these produce
(frontend brief §4.1), so a field renamed here is a breaking change and a
field added as required here breaks their build.

Two rules that are enforced rather than hoped for:

- `data/fixtures/*.json` is generated by instantiating these models
  (scripts/gen_fixtures.py), so a fixture cannot drift from the response shape.
  tests/test_schemas.py validates every fixture back through its model.
- No `dict[str, Any]` on a request body. Brief §13 requires explicit types,
  bounds and enums on every public input.

Field order follows the brief's JSON examples so the two read side by side.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Annotated, Generic, Literal, TypeVar

from pydantic import BaseModel, ConfigDict, EmailStr, Field, StringConstraints

from db.models import DocSource, Resolver, RoutingBucket, UserRole

# ── shared ───────────────────────────────────────────────────────────────────

T = TypeVar("T")

Unit = Annotated[float, Field(ge=0.0, le=1.0)]
"""A score the API promises is in [0,1]. Matches the DB CHECK constraints."""

ShortText = Annotated[str, StringConstraints(min_length=1, max_length=512, strip_whitespace=True)]


class Schema(BaseModel):
    """Base for every model here.

    `extra="forbid"` on requests is what turns a typo in a client payload into
    a 422 with a field message instead of a silently ignored parameter.
    """

    model_config = ConfigDict(extra="forbid", from_attributes=True)


class PaginationOut(Schema):
    cursor: str | None = Field(default=None, description="The cursor this page was fetched with.")
    next_cursor: str | None = Field(default=None, description="Pass as `cursor` for the next page.")
    has_more: bool
    limit: int = Field(ge=1, le=100)


class Paginated(Schema, Generic[T]):
    """Brief §3: collections are always wrapped, single resources never are."""

    data: list[T]
    pagination: PaginationOut


class ErrorBody(Schema):
    code: str
    message: str
    status: int
    request_id: str
    details: dict[str, object] = Field(default_factory=dict)


class ErrorEnvelope(Schema):
    """Documented in OpenAPI so the frontend can generate its error types too."""

    error: ErrorBody


# ── auth (§4) ────────────────────────────────────────────────────────────────


class RegisterRequest(Schema):
    email: EmailStr
    # Policy is enforced server-side in core.security.validate_password, which
    # also checks the common-password denylist. The bound here is only the
    # cheap structural check so an absurd payload never reaches argon2.
    password: Annotated[str, StringConstraints(min_length=12, max_length=256)]
    org_name: Annotated[str, StringConstraints(min_length=2, max_length=120, strip_whitespace=True)]


class LoginRequest(Schema):
    email: EmailStr
    password: Annotated[str, StringConstraints(min_length=1, max_length=256)]


class UserOut(Schema):
    id: uuid.UUID
    email: str
    role: UserRole
    org_id: uuid.UUID


class AuthResponse(Schema):
    """The refresh token is NOT here.

    It is set as an HttpOnly cookie and the frontend never touches it
    (brief §4). Putting it in a JSON body would make it readable by any script
    on the page, which defeats the point of rotation.
    """

    user: UserOut
    access_token: str
    token_type: Literal["bearer"] = "bearer"  # noqa: S105 - a scheme name, not a secret  # noqa: S105 - a scheme name, not a secret
    expires_in: int = Field(description="Access token lifetime in seconds.")


class MeResponse(Schema):
    id: uuid.UUID
    email: str
    role: UserRole
    org_id: uuid.UUID
    org_name: str
    # Frontend gates affordances on these strings, never on `role`
    # (frontend brief §4.4).
    permissions: list[str]


class MemberOut(Schema):
    """A row in the settings members table.

    Deliberately not `UserOut`: that one carries `org_id`, which is the same
    value for every row here and is already known from `/auth/me`. `created_at`
    is what the table actually needs, to show joining order.
    """

    id: uuid.UUID
    email: str
    role: UserRole
    created_at: datetime


# ── documents (§5) ───────────────────────────────────────────────────────────


class DocumentIngested(Schema):
    id: uuid.UUID
    title: str
    source: DocSource
    chars: int


class UploadResponse(Schema):
    job_id: uuid.UUID
    documents: list[DocumentIngested]
    duplicates_skipped: int


Scenario = Literal["meridian_shell_ring", "clean_baseline", "invoice_flood"]


class SeedRequest(Schema):
    """`train_corpus` is deliberately absent from the enum.

    It is the tagger/GAT training split and must never be servable through the
    API — an evaluated insight drawn from training data would contaminate every
    number the project reports.
    """

    scenario: Scenario = "meridian_shell_ring"


class MentionOut(Schema):
    entity_id: uuid.UUID
    surface: str
    entity_type: str
    char_start: int = Field(ge=0)
    char_end: int = Field(ge=0)
    tagger_conf: Unit


class SpanOut(Schema):
    insight_id: uuid.UUID
    char_start: int = Field(ge=0)
    char_end: int = Field(ge=0)
    relation: str
    confidence: Unit
    routing: RoutingBucket


class DocumentSummary(Schema):
    id: uuid.UUID
    title: str
    source: DocSource
    received_at: datetime
    chars: int
    insight_count: int


class DocumentDetail(Schema):
    """`raw_text` is the single source of truth for every offset in the system.

    The frontend slices this exact string to render highlights and must not
    normalize whitespace, trim, or pass it through a markdown renderer
    (brief §5). It is rendered into `textContent`, never `innerHTML`.
    """

    id: uuid.UUID
    title: str
    source: DocSource
    received_at: datetime
    raw_text: str
    spans: list[SpanOut]
    mentions: list[MentionOut]


# ── ingest (§5) ──────────────────────────────────────────────────────────────


JobStateName = Literal[
    "queued", "tagging", "parsing", "relating", "scoring", "routing", "done", "failed"
]


class StageProgress(Schema):
    tagging: Unit = 0.0
    parsing: Unit = 0.0
    relating: Unit = 0.0
    scoring: Unit = 0.0
    routing: Unit = 0.0


class JobOut(Schema):
    id: uuid.UUID
    state: JobStateName
    docs_total: int
    docs_done: int
    insights_found: int
    stage_progress: StageProgress
    started_at: datetime | None = None
    finished_at: datetime | None = None
    error: str | None = None


# ── insights (§6) ────────────────────────────────────────────────────────────


class EntityRef(Schema):
    id: uuid.UUID
    canonical: str
    entity_type: str


class Citation(Schema):
    document_id: uuid.UUID
    document_title: str
    char_start: int = Field(ge=0)
    char_end: int = Field(ge=0)
    sentence_text: str


class TrustScores(Schema):
    confidence: Unit
    vacuity: Unit
    dissonance: Unit
    # Null until the fuzzer job has run. Null is not zero — zero would claim
    # the insight was tested and found robust.
    fragility: Unit | None = None


class NemotronInfo(Schema):
    run_id: uuid.UUID
    rationale: str
    latency_ms: int


class InsightOut(Schema):
    id: uuid.UUID
    relation: str
    subject: EntityRef
    object: EntityRef
    citation: Citation
    trust: TrustScores
    routing: RoutingBucket
    resolved_by: Resolver
    nemotron: NemotronInfo | None = None
    # True when the cascade gated this insight for escalation but the upstream
    # hard-failed, so the classical decision stands. Frontend renders a
    # "reviewed classically" marker (frontend brief §4.3).
    degraded: bool = False
    attention_available: bool
    created_at: datetime


class AttentionEdge(Schema):
    edge_id: str
    src_token: str
    dst_token: str
    weight: Unit
    src_idx: int = Field(ge=0)
    dst_idx: int = Field(ge=0)


class GraphNeighborhood(Schema):
    node_ids: list[uuid.UUID]
    depth: int = Field(ge=1, le=3)


class AblationHistoryItem(Schema):
    id: uuid.UUID
    masked_edges: list[str]
    confidence_before: Unit
    confidence_after: Unit
    load_bearing: bool
    created_at: datetime


class FragilityTrialOut(Schema):
    perturbation: Literal["synonym", "rename", "boilerplate", "reorder", "punctuation"]
    label_flipped: bool
    conf_delta: float = Field(ge=-1.0, le=1.0)
    relation_lost: bool


class InsightDetail(InsightOut):
    attention: list[AttentionEdge]
    tokens: list[str]
    graph_neighborhood: GraphNeighborhood
    ablation_history: list[AblationHistoryItem]
    fragility_trials: list[FragilityTrialOut]


class InsightStats(Schema):
    total: int
    by_routing: dict[str, int]
    by_resolver: dict[str, int]
    mean_confidence: Unit
    high_vacuity_count: int
    documents_ingested: int


# ── graph (§7) ───────────────────────────────────────────────────────────────


class GraphNode(Schema):
    id: uuid.UUID
    canonical: str
    entity_type: str
    mention_count: int
    degree: int
    # Normalized composite of degree centrality, cycle participation and mean
    # incident-edge routing severity. Weights are in config and reported so the
    # number is not magic.
    risk: Unit
    flags: list[str]


class GraphEdge(Schema):
    id: uuid.UUID
    source: uuid.UUID
    target: uuid.UUID
    relation: str
    confidence: Unit
    vacuity: Unit
    routing: RoutingBucket
    insight_ids: list[uuid.UUID]
    # Number of distinct insights supporting this relation. Drives stroke width.
    weight: int = Field(ge=1)


class GraphCycle(Schema):
    node_ids: list[uuid.UUID]
    length: int = Field(ge=2)
    relation: str
    risk: Unit


class GraphResponse(Schema):
    """Cycles are computed server-side via Tarjan SCC over the OWNED_BY
    subgraph. The frontend must not attempt client-side cycle detection
    (frontend brief §9); it renders what is here."""

    nodes: list[GraphNode]
    edges: list[GraphEdge]
    cycles: list[GraphCycle]
    truncated: bool


class NeighborOut(Schema):
    entity: GraphNode
    relation: str
    direction: Literal["in", "out"]
    confidence: Unit
    insight_ids: list[uuid.UUID]


class EntityDocument(Schema):
    id: uuid.UUID
    title: str
    mention_count: int


class EntityDetailNode(GraphNode):
    first_seen: datetime


class EntityDetail(Schema):
    entity: EntityDetailNode
    aliases: list[str]
    neighbors: list[NeighborOut]
    documents: list[EntityDocument]
    insight_count: int


# ── ablation (§8) ────────────────────────────────────────────────────────────


class AblationRequest(Schema):
    masked_edges: Annotated[list[str], Field(min_length=1, max_length=32)]
    # `zero` sets the attention weight to 0 and renormalizes; `uniform`
    # replaces surviving weights with uniform attention.
    mode: Literal["zero", "uniform"] = "zero"


class AblationState(Schema):
    confidence: Unit
    vacuity: Unit
    routing: RoutingBucket
    relation: str


class AblationDelta(Schema):
    confidence: float = Field(ge=-1.0, le=1.0)
    vacuity: float = Field(ge=-1.0, le=1.0)
    routing_changed: bool


class AblationResponse(Schema):
    run_id: uuid.UUID
    insight_id: uuid.UUID
    masked_edges: list[str]
    before: AblationState
    after: AblationState
    delta: AblationDelta
    # True iff |delta.confidence| > 0.10 OR routing changed.
    load_bearing: bool
    # Template-filled, NOT generated text. Templates live in
    # ml/ablation/templates.py and the voice layer reads this field verbatim,
    # so it is part of the no-hallucination guarantee (brief §8).
    interpretation: str
    latency_ms: int


# ── routing / cascade (§9) ───────────────────────────────────────────────────


class GateConfig(Schema):
    vacuity_threshold: Unit
    policy: str


class CascadeVolume(Schema):
    total_insights: int
    handled_classically: int
    escalated_to_nemotron: int
    escalation_rate: Unit
    llm_calls_avoided: int


class CascadeLatency(Schema):
    classical_p50_ms: int
    classical_p95_ms: int
    nemotron_p50_ms: int
    nemotron_p95_ms: int


class CascadeAgreement(Schema):
    nemotron_upheld_classical: int
    nemotron_overrode_classical: int
    override_rate: Unit


class RoutingSummary(Schema):
    gate: GateConfig
    volume: CascadeVolume
    latency: CascadeLatency
    agreement: CascadeAgreement
    distribution: dict[str, int]


class NemotronRunOut(Schema):
    """The "show your work" table. Brief §14: this is what the Beyond the
    Chatbot judges will actually want to look at."""

    id: uuid.UUID
    insight_id: uuid.UUID | None
    prompt_sha: str = Field(min_length=64, max_length=64)
    decision: RoutingBucket
    rationale: str
    latency_ms: int
    input_tokens: int | None = None
    output_tokens: int | None = None
    degraded: bool = False
    created_at: datetime


# ── evals (§10) ──────────────────────────────────────────────────────────────


class Correlation(Schema):
    spearman: float = Field(ge=-1.0, le=1.0)
    pearson: float = Field(ge=-1.0, le=1.0)
    p_value: float = Field(ge=0.0, le=1.0)


class ScatterPoint(Schema):
    insight_id: uuid.UUID
    vacuity: Unit
    fragility: Unit
    routing: RoutingBucket


class PerturbationStat(Schema):
    perturbation: str
    flip_rate: Unit
    mean_abs_conf_delta: Unit
    relation_loss_rate: Unit


class QuartileRow(Schema):
    vacuity_quartile: int = Field(ge=1, le=4)
    vacuity_range: tuple[Unit, Unit]
    mean_fragility: Unit
    flip_rate: Unit


class FragilityEval(Schema):
    """Brief §10: the single most important response object in the project.

    Whatever the Spearman comes out as is what this returns. There is no code
    path in the fuzzer that tunes it.
    """

    n_insights: int
    n_trials: int
    perturbations: list[str]
    correlation: Correlation
    scatter: list[ScatterPoint]
    by_perturbation: list[PerturbationStat]
    quartile_table: list[QuartileRow]
    interpretation: str


class ConfusionMatrix(Schema):
    labels: list[str]
    matrix: list[list[int]]


class PerClassMetrics(Schema):
    bucket: RoutingBucket
    precision: Unit
    recall: Unit
    f1: Unit
    support: int


class CascadeBaseline(Schema):
    classical_only_accuracy: Unit
    nemotron_on_everything_accuracy: Unit
    cascade_accuracy: Unit
    cascade_llm_calls: int
    nemotron_on_everything_llm_calls: int
    interpretation: str


class DocumentedFailure(Schema):
    """`note` is written by hand and is worth more to the Nemotron judges than
    every clean metric above it. This list never ships empty (brief §10)."""

    case_id: uuid.UUID
    insight_id: uuid.UUID | None
    ground_truth: RoutingBucket
    predicted: RoutingBucket
    sentence_text: str
    note: str


class RoutingEval(Schema):
    n_cases: int
    confusion_matrix: ConfusionMatrix
    per_class: list[PerClassMetrics]
    macro_f1: Unit
    accuracy: Unit
    cascade_baseline: CascadeBaseline
    documented_failures: list[DocumentedFailure]


class CalibrationBin(Schema):
    bin_lo: Unit
    bin_hi: Unit
    avg_conf: Unit
    accuracy: Unit
    count: int


class CalibrationSnapshotOut(Schema):
    id: uuid.UUID
    label: Literal["baseline", "post_recalibration"]
    temperature: float = Field(gt=0.0)
    ece: Unit
    mce: Unit
    brier: Unit
    bins: list[CalibrationBin]
    created_at: datetime


class CalibrationEval(Schema):
    snapshots: list[CalibrationSnapshotOut]
    current_snapshot_id: uuid.UUID | None
    hard_negatives_logged: int


# ── calibration (§10) ────────────────────────────────────────────────────────


class RecalibrateRequest(Schema):
    method: Literal["temperature_scaling"] = "temperature_scaling"


class CalibrationMetrics(Schema):
    temperature: float = Field(gt=0.0)
    ece: Unit
    mce: Unit
    brier: Unit
    bins: list[CalibrationBin]


class CalibrationImprovement(Schema):
    ece_absolute: float
    ece_relative: float


class RecalibrateResponse(Schema):
    before: CalibrationMetrics
    after: CalibrationMetrics
    improvement: CalibrationImprovement
    n_hard_negatives: int
    elapsed_ms: int
    snapshot_id: uuid.UUID


# ── voice (§11) ──────────────────────────────────────────────────────────────


BriefingScope = Literal["flagged", "escalated", "all_new"]


class BriefingRequest(Schema):
    scope: BriefingScope = "flagged"
    max_items: int = Field(default=3, ge=1, le=5)
    voice_id: ShortText = "default"


class TranscriptSegment(Schema):
    """`insight_id` is what drives transcript-to-feed highlight sync, which is
    the moment that sells the voice track (frontend brief §12.1)."""

    segment_id: str
    start_ms: int = Field(ge=0)
    end_ms: int = Field(ge=0)
    text: str
    insight_id: uuid.UUID | None = None


class BriefingResponse(Schema):
    briefing_id: uuid.UUID
    audio_url: str
    duration_ms: int = Field(ge=0)
    transcript: list[TranscriptSegment]
    insight_ids: list[uuid.UUID]
    generated_at: datetime
    # True when this is the prerecorded fallback rather than live synthesis, so
    # the frontend can show its honest "playing recorded briefing" note.
    is_fallback: bool = False
    # False when there is no audio to play and `transcript` is all there is:
    # live synthesis failed AND no briefing was ever recorded. The frontend
    # should skip the player and render the transcript with its insight sync
    # intact (frontend brief §12.1 — that sync is the beat that sells the
    # track, and it does not need audio to work).
    #
    # Additive with a default of True, deliberately: making `audio_url`
    # nullable would break the generated TypeScript for every existing
    # consumer, exactly as adding `degraded` did not. Old clients that ignore
    # this field behave as before.
    audio_available: bool = True


VoiceIntent = Literal[
    "explain_flag",
    "show_source",
    "list_flagged",
    "entity_summary",
    "confidence_query",
    "dismiss",
    "unknown",
]


class AskResponse(Schema):
    """`answer_text` is assembled from templates over structured fields plus the
    cited source sentence. No generative model writes it (brief §11)."""

    question_id: uuid.UUID
    heard: str
    stt_confidence: Unit
    intent: VoiceIntent
    resolved_insight_id: uuid.UUID | None
    answer_text: str
    citation: Citation | None
    ablation_run_id: uuid.UUID | None
    audio_url: str | None
    duration_ms: int = Field(ge=0)


# ── eval job (plan §1.8 — endpoint addition) ─────────────────────────────────


class FuzzerRunResponse(Schema):
    """Fuzzing is a job, not part of ingest.

    Ingest must finish in under 30s for the demo; 214 insights x 5 perturbations
    is 1,070 pipeline passes. Owner-only, and the eval page reads finished rows.
    """

    job_id: uuid.UUID
    n_insights: int
    n_trials_planned: int
    started_at: datetime
